name: lambda-build-deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ECR Repository
        run: |
          echo "ECR_REPOSITORY=${{ vars.ECR_REPOSITORY }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: copy google-service
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON }}
          GOOGLE_SERVICE_KARIYA: ${{ secrets.GOOGLE_SERVICE_KARIYA_JSON }}
          GOOGLE_SERVICE_YAMATO: ${{ secrets.GOOGLE_SERVICE_YAMATO_JSON }}
        run:  |
          echo $GOOGLE_SERVICE | base64 --decode --ignore-garbage > ./go/fcm/default-serviceAccountKey.json
          echo $GOOGLE_SERVICE_KARIYA | base64 --decode --ignore-garbage > ./go/fcm/kariya-serviceAccountKey.json
          echo $GOOGLE_SERVICE_YAMATO | base64 --decode --ignore-garbage > ./go/fcm//yamato-serviceAccountKey.json

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            "APP_VERSION=${GITHUB_SHA}"
          push: true
          tags: ${{ env.ECR_REPOSITORY }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: update Lambda function
        run: |
          aws lambda update-function-code --function-name ${{ vars.LAMBDA_FUNCTION_NAME }} --image-uri ${{ vars.ECR_REPOSITORY }}:latest

